name 'msodbcsql'
maintainer 'colourmeamused'
maintainer_email '<maintainer> AT outlook com'
license 'apachev2'
description 'Installs/Configures cockpit'
long_description 'Configures Unix ODBC and Microsoft ODBC Driver for SQL Server on Linux (RHEL 7.x)'
version '0.1.0'
source_url 'https://github.com/colourmeamused/odbc_sqlserver-cookbook.git'
issues_url 'https://github.com/colourmeamused/odbc_sqlserver-cookbook/issues'
supports 'rhel', '>= 7.1'
depends 'redhat_subscription_manager', '~> 0.5.0'
depends 'firewalld', '~> 1.1.1'
depends 'selinux_policy', '~> 0.9.5'
depends 'augeas'
depends 'chef-vault'
depends 'ark'
