name 'odbc_sqlserver'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures odbc_sqlserver'
long_description 'Installs/Configures odbc_sqlserver'
version '0.1.0'
